spring.application.name=UTN-movies-library-backend
server.port=8091
spring.datasource.url=jdbc:postgresql://localhost:3306/movieslibrary
spring.datasource.username=REPLACE_WITH_USER
spring.datasource.password=REPLACE_WITH_PWD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
jwt.secret="misuperclavesecretadelgobierno123"
jwt.expiration=3600000